---
sudo: required
language: c
matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
  - os: linux
    dist: trusty
    compiler: clang
  - os: linux
    dist: trusty
    compiler: clang
    env: CLANG=4.0
  - os: osx
    osx_image: xcode8.3
    compiler: clang
  allow_failures:
  - os: osx
  - env: CLANG=4.0
addons:
  apt:
    packages:
      - python-docutils
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install docutils nghttp2;
    fi
  - if [[ "$CLANG" == "4.0" ]]; then
      wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key |
        sudo apt-key add -;
      sudo apt-add-repository -y
        'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main';
      sudo apt-get update;
      sudo apt-get install -y clang-4.0;
      export CC="clang-4.0";
      export CONFIGURE_ARGS="--enable-asan --enable-ubsan";
      export ASAN_OPTIONS="detect_odr_violation=0,detect_leaks=0";
    fi
  - ./autogen.sh
  - ./configure ${CONFIGURE_ARGS}
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export PYTHONPATH=`brew --prefix`/lib/python2.7/site-packages; fi
  - make -j3 check VERBOSE=1
